apiVersion: v1
kind: Service
metadata:
  name: fl-host
  namespace: federated-learning
spec:
  selector:
    app: fl-host
  ports:
    - protocol: TCP
      port: 31000
      targetPort: 31000
  type: ClusterIP
